### ISSUE TITLE
Need to store the 'feminine/masculine', 'heritage/modern' values retrieved in the New Form 'UserCreationScreen' somewhere

### ISSUE THREAD

**Issue by ThomasRCoupe** [JSCooke/MPAi#73]
The form 'UserCreationScreen' obtains the 'feminine/masculine', 'heritage/modern', but has nowhere to put them. Hook this up when possible.

**Comment by cookEsandcream** [comment]
Seems like UserManagement would be a good place.
Also, if possible, use them to create Category and Speaker objects, not just strings.

**Comment by cookEsandcream** [comment]
Currently they are associated with the VoiceType Enum, and stored in the MPAi user class.
